import { calculatorIcon } from './calculator';
import { cloudDownloadIcon } from './cloud-download';
import { cloudUploadIcon } from './cloud-upload';
import { downloadIcon } from './download';
import { paperClipIcon } from './paper-clip';
import { refreshIcon } from './refresh';
import { rssIcon } from './rss';
import { solidFireIcon } from './solid-fire';
import { solidLogoutIcon } from './solid-logout';
import { solidQuestionMarkCircleIcon } from './solid-question-mark-circle';
import { solidServerIcon } from './solid-server';
export const imsaferIcons = [calculatorIcon, cloudDownloadIcon, cloudUploadIcon, downloadIcon, paperClipIcon, refreshIcon, rssIcon, solidFireIcon, solidLogoutIcon, solidQuestionMarkCircleIcon, solidServerIcon];
